# Server port for the API Gateway
server.port=8080

# Spring Cloud Gateway Routes
spring.cloud.gateway.routes[0].id=document-service-route
spring.cloud.gateway.routes[0].uri=http://localhost:8082
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/documents/**
