# Server Port
server.port=8081

# PostgreSQL DataSource Properties
spring.datasource.url=jdbc:postgresql://localhost:5432/sistradoc_users
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Properties
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# Initialize the database using schema.sql
spring.sql.init.mode=always
